---
collections:
  - name: community.crypto
    version: "2.23.0"
  - name: community.docker
    version: "3.13.0"
  - name: community.general
    version: "9.5.0"
  - name: community.vagrant
    version: "1.1.0"
