---
- hosts: all

  vars_files:
    # Use Ansible Vault to encrypt this file:
    # ansible-vault encrypt group_vars/secrets.yml
    - group_vars/secrets.yml

  roles:
    - role: security
      tags: ['security', 'setup']
    - role: docker_host
      tags: ['docker', 'setup']
    - role: traefik_proxy
      tags: ['traefik', 'setup']
    - role: vpn
      tags: ['vpn', 'setup']
    - role: dns
      tags: ['dns', 'setup']
    - role: system_tools
      tags: ['tools', 'setup']
