---
# tasks file for app_deployment
- name: "Fail if app_repo is not set"
  ansible.builtin.fail:
    msg: "The 'app_repo' variable is set to the default placeholder 'your_app_repo.git'. Please provide a valid Git repository URL in app_deployment/vars/main.yml."
  when: app_repo == 'your_app_repo.git'
  run_once: true

- name: Ensure required packages are installed
  ansible.builtin.apt:
    name:
      - git
      - acl
    state: present
    update_cache: yes

- name: Check if the git repository is valid and accessible
  ansible.builtin.command:
    cmd: "git ls-remote {{ app_repo }}"
  register: git_check
  changed_when: false
  failed_when: false # We handle the failure manually
  run_once: true

- name: Fail if git repository is not accessible
  ansible.builtin.fail:
    msg: "The git repository '{{ app_repo }}' is not accessible. Please check the URL and access rights. Error: {{ git_check.stderr }}"
  when: git_check.rc != 0
  run_once: true

- name: Set app_user fact
  ansible.builtin.set_fact:
    app_user: "{{ (app_repo | basename | regex_replace('.git$', ''))[:32] }}"

- name: Create a new system user for the application
  ansible.builtin.user:
    name: "{{ app_user }}"
    shell: /usr/sbin/nologin
    system: yes
    create_home: yes
    groups: traefik
    append: yes

- name: Ensure remote_tmp directory exists for app_user
  ansible.builtin.file:
    path: "/home/{{ app_user }}/.ansible/tmp"
    state: directory
    mode: '0755'
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
  become: yes

- name: Set up rootless docker for app user
  ansible.builtin.include_tasks: rootless_docker.yml

- name: Create app directory
  ansible.builtin.file:
    path: "/home/{{ app_user }}/app"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'

- name: Clone the application repository
  ansible.builtin.git:
    repo: "{{ app_repo }}"
    dest: "/home/{{ app_user }}/app"
    accept_hostkey: yes
    force: yes
    version: "{{ app_branch }}"
  become: yes
  become_user: "{{ app_user }}"

- name: Setup environment variables
  ansible.builtin.include_tasks: setup_env.yml

- name: Setup and run Docker
  ansible.builtin.include_tasks: setup_docker.yml

- name: Setup Traefik routing rules
  ansible.builtin.include_tasks: setup_proxy_rules.yml

- name: Create internal DNS record
  ansible.builtin.copy:
    dest: "/etc/dnsmasq.d/{{ app_user }}.conf"
    content: "address=/{{ app_domain_name }}.internal/10.0.0.1"
    mode: '0644'
  become: yes
  notify: restart dnsmasq

- name: Register app with webhook listener
  ansible.builtin.template:
    src: webhook_config.json.j2
    dest: "/opt/webhook/conf.d/{{ app_user }}.json"
    owner: root
    group: webhook
    mode: '0640'
  become: yes
  notify: restart webhook
